JLPTWeb/Models/B_News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_News
    {
        public int NewsId { get; set; }
        public string Title { get; set; }
        public string NewContent { get; set; }
        public string TitleWithRuby { get; set; }
        public string NewContentWithRuby { get; set; }
        public string ImagePath { get; set; }
        public string MoviePath { get; set; }
        public string NewIdNHK { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string NewsWebUrl { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }
}

JLPTWeb/Controllers/B_NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JLPTWeb.Models;
using PagedList.Mvc;
using PagedList;

namespace JLPTWeb.Controllers
{
    public class B_NewsController : Controller
    {
        private JLPTDatabaseEntities db = new JLPTDatabaseEntities();

        // GET: B_News
        public ActionResult Index(int? id, int?page)
        {
            var lstNews = db.B_News.Where(s => s.ActiveFlag == 1).OrderByDescending(s => s.NewsDate).Take(30);
            if (id == null)
            {
                ViewBag.lstNews = lstNews.FirstOrDefault();
            } else
            {
                ViewBag.lstNews = lstNews.Where(s => s.NewsId == id).FirstOrDefault();
            }
            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(lstNews.ToPagedList(pageNumber, pageSize));
        }

        // GET: B_News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            B_News b_News = db.B_News.Find(id);
            if (b_News == null)
            {
                return HttpNotFound();
            }
            return View(b_News);
        }

        // GET: B_News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: B_News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NewsId,Title,NewContent,ImagePath,MoviePath,NewIdNHK,NewsDate,NewsWebUrl,ActiveFlag,CreateTime,UpdateTime,DeleteTime,TitleWithRuby,NewContentWithRuby")] B_News b_News)
        {
            if (ModelState.IsValid)
            {
                db.B_News.Add(b_News);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(b_News);
        }

        // GET: B_News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            B_News b_News = db.B_News.Find(id);
            if (b_News == null)
            {
                return HttpNotFound();
            }
            return View(b_News);
        }

        // POST: B_News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsId,Title,NewContent,ImagePath,MoviePath,NewIdNHK,NewsDate,NewsWebUrl,ActiveFlag,CreateTime,UpdateTime,DeleteTime,TitleWithRuby,NewContentWithRuby")] B_News b_News)
        {
            if (ModelState.IsValid)
            {
                db.Entry(b_News).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(b_News);
        }

        // GET: B_News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            B_News b_News = db.B_News.Find(id);
            if (b_News == null)
            {
                return HttpNotFound();
            }
            return View(b_News);
        }

        // POST: B_News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            B_News b_News = db.B_News.Find(id);
            db.B_News.Remove(b_News);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JLPTWeb/Views/B_News/Index.cshtml
@model PagedList.IPagedList<JLPTWeb.Models.B_News>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_NotRight.cshtml";
}

@{
    var news = (JLPTWeb.Models.B_News)ViewBag.lstNews;
}

@if (news != null) { 
<div class="col-sm-8" style="padding-right:20px">
    <div class="row">
        <div class="article-main__title">@MvcHtmlString.Create(news.TitleWithRuby)</div><br />
        <p style="color:#999">@news.NewsDate</p>
        <img src="@news.ImagePath" class="img-rounded" alt="Cinque Terre" style="width:100%; margin-bottom:10px;">
    </div>
    <div class="row nihon-text">
        @MvcHtmlString.Create(news.NewContentWithRuby)
    </div>
    <div class="row" style="text-align:right">
        ソース：<a target="blank" href="https://www3.nhk.or.jp/news/">NHK ニュース</a>
    </div>
</div>
}
<div class="col-sm-4" style="border-left: solid 1px #CD5C5C;">
    <h1 class="sidebar-section__title" style="margin-top:0px"><ruby>新<rt>あたら</rt></ruby>しいニュース</h1>
    @foreach (var item in Model)
    {
        <div class="row" style="position:relative">
            <a href="/B_News/Index?Id=@item.NewsId&page=@Model.PageNumber">
                <div class="col-md-6">
                    <img src="@item.ImagePath" alt="Lights" style="width:100%">
                </div>
                <div class="nihon-text-title">
                    <p style="color:#808080">@item.Title</p>
                </div>
                <div style="color:#999;position:absolute;bottom:0;right:15px">@item.NewsDate</div>
            </a>
        </div>
        <hr style="width:100%;border-width:1px;border-color:#CD5C5C" />
    }
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", "B_News", new { page, Id = @news.NewsId }), new PagedListRenderOptions { MaximumPageNumbersToDisplay = 4 })
</div>